package alut

// #cgo  darwin  CFLAGS: -I/usr/local/include 
// #cgo  darwin LDFLAGS: -L/usr/local/lib -lalut -framework OpenAL 
// #include <stdlib.h>
// #include <AL/alut.h>
import "C"

const (
	API_MAJOR_VERSION = C.ALUT_API_MAJOR_VERSION
	API_MINOR_VERSION = C.ALUT_API_MINOR_VERSION

	ERROR_NO_ERROR                  = C.ALUT_ERROR_NO_ERROR
	ERROR_OUT_OF_MEMORY             = C.ALUT_ERROR_OUT_OF_MEMORY
	ERROR_INVALID_ENUM              = C.ALUT_ERROR_INVALID_ENUM
	ERROR_INVALID_VALUE             = C.ALUT_ERROR_INVALID_VALUE
	ERROR_INVALID_OPERATION         = C.ALUT_ERROR_INVALID_OPERATION
	ERROR_NO_CURRENT_CONTEXT        = C.ALUT_ERROR_NO_CURRENT_CONTEXT
	ERROR_AL_ERROR_ON_ENTRY         = C.ALUT_ERROR_AL_ERROR_ON_ENTRY
	ERROR_ALC_ERROR_ON_ENTRY        = C.ALUT_ERROR_ALC_ERROR_ON_ENTRY
	ERROR_OPEN_DEVICE               = C.ALUT_ERROR_OPEN_DEVICE
	ERROR_CLOSE_DEVICE              = C.ALUT_ERROR_CLOSE_DEVICE
	ERROR_CREATE_CONTEXT            = C.ALUT_ERROR_CREATE_CONTEXT
	ERROR_MAKE_CONTEXT_CURRENT      = C.ALUT_ERROR_MAKE_CONTEXT_CURRENT
	ERROR_DESTROY_CONTEXT           = C.ALUT_ERROR_DESTROY_CONTEXT
	ERROR_GEN_BUFFERS               = C.ALUT_ERROR_GEN_BUFFERS
	ERROR_BUFFER_DATA               = C.ALUT_ERROR_BUFFER_DATA
	ERROR_IO_ERROR                  = C.ALUT_ERROR_IO_ERROR
	ERROR_UNSUPPORTED_FILE_TYPE     = C.ALUT_ERROR_UNSUPPORTED_FILE_TYPE
	ERROR_UNSUPPORTED_FILE_SUBTYPE  = C.ALUT_ERROR_UNSUPPORTED_FILE_SUBTYPE
	ERROR_CORRUPT_OR_TRUNCATED_DATA = C.ALUT_ERROR_CORRUPT_OR_TRUNCATED_DATA

	WAVEFORM_SINE       = C.ALUT_WAVEFORM_SINE
	WAVEFORM_SQUARE     = C.ALUT_WAVEFORM_SQUARE
	WAVEFORM_SAWTOOTH   = C.ALUT_WAVEFORM_SAWTOOTH
	WAVEFORM_WHITENOISE = C.ALUT_WAVEFORM_WHITENOISE
	WAVEFORM_IMPULSE    = C.ALUT_WAVEFORM_IMPULSE

	LOADER_BUFFER = C.ALUT_LOADER_BUFFER
	LOADER_MEMORY = C.ALUT_LOADER_MEMORY
)
